---
title: "Create a Virtual Machine"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
# library(googleCloudRunner)
library(shiny)
library(metagce)
library(gcloud)
library(googleAuthR)
library(dplyr)
library(tibble)
library(googleComputeEngineR)
library(googleCloudStorageR)
library(DT)
library(shinyjs)
```

```{r auth, include = FALSE}
options(httr_oauth_cache = FALSE)
token = gargle::credentials_gce()
googleAuthR::gar_auth(token = token, cache = FALSE)
```

```{r project_setup, include=FALSE}
project = metagce::gce_project()
if (nchar(project) == 0) {
  projects = gcloud::gcloud_projects_list()$projectId
  project = projects[1]
} else {
  projects = project
}
projects = gcloud::gcloud_projects_list()$projectId
```


```{r, include = FALSE}
if (!is.null(project)) {
# zones = c("us-east4-c", 
#           gcloud::gcloud_compute_zones_list(
#             project = project)$name)
}
zones = c("us-east4-c", "us-east1-b", "us-east1-c", "us-east1-d", "us-east4-c", 
"us-east4-b", "us-east4-a", "us-central1-c", "us-central1-a", 
"us-central1-f", "us-central1-b", "us-west1-b", "us-west1-c", 
"us-west1-a", "europe-west4-a", "europe-west4-b", "europe-west4-c", 
"europe-west1-b", "europe-west1-d", "europe-west1-c", "europe-west3-c", 
"europe-west3-a", "europe-west3-b", "europe-west2-c", "europe-west2-b", 
"europe-west2-a", "asia-east1-b", "asia-east1-a", "asia-east1-c", 
"asia-southeast1-b", "asia-southeast1-a", "asia-southeast1-c", 
"asia-northeast1-b", "asia-northeast1-c", "asia-northeast1-a", 
"asia-south1-c", "asia-south1-b", "asia-south1-a", "australia-southeast1-b", 
"australia-southeast1-c", "australia-southeast1-a", "southamerica-east1-b", 
"southamerica-east1-c", "southamerica-east1-a", "asia-east2-a", 
"asia-east2-b", "asia-east2-c", "asia-northeast2-a", "asia-northeast2-b", 
"asia-northeast2-c", "asia-northeast3-a", "asia-northeast3-b", 
"asia-northeast3-c", "asia-south2-a", "asia-south2-b", "asia-south2-c", 
"asia-southeast2-a", "asia-southeast2-b", "asia-southeast2-c", 
"australia-southeast2-a", "australia-southeast2-b", "australia-southeast2-c", 
"europe-central2-a", "europe-central2-b", "europe-central2-c", 
"europe-north1-a", "europe-north1-b", "europe-north1-c", "europe-west6-a", 
"europe-west6-b", "europe-west6-c", "northamerica-northeast1-a", 
"northamerica-northeast1-b", "northamerica-northeast1-c", "northamerica-northeast2-a", 
"northamerica-northeast2-b", "northamerica-northeast2-c", "southamerica-west1-a", 
"southamerica-west1-b", "southamerica-west1-c", "us-west2-a", 
"us-west2-b", "us-west2-c", "us-west3-a", "us-west3-b", "us-west3-c", 
"us-west4-a", "us-west4-b", "us-west4-c")
zones = unique(zones)
```


Inputs {.sidebar}
-------------------------------------


```{r}
shinyjs::useShinyjs(rmd = TRUE)
selectInput(inputId = "project", label = "Project:", choices = projects, selected = projects[1])

textInput(
  "vm_name", "Name for VM (please check running):"
)

selectInput(inputId = "zone", label = "Zone to Make VM:", choices = zones, selected = zones[1])

numericInput("gb", "Disk size (Gb)", value = 80, min = 1, max = 1000, step = 1L)

textInput(
  "dynamic_image", "Docker Image to Run:", 
  value = "us-docker.pkg.dev/streamline-resources/streamline-private-repo/streamliner"
)
uiOutput("machiner")


shinyjs::disabled(actionButton("create_image", "Create Image"))
```

Column {data-width=600}
-------------------------------------

```{r, include=FALSE}
values = reactiveValues(refresh = FALSE,
                        vm = NULL)
shinyjs::disable("create_image")
reactive({
  gcloud::gcloud_project_set(project = input$project)
  googleComputeEngineR::gce_global_project(project = input$project)
})
```

### Description of Machine Types

```{r}
# x = gcloud::gcloud_compute_machineTypes_list()
# x = x[is.na(x$deprecated$state),]
# x = x %>%
#   mutate(memory = round(memoryMb/1024)) %>%
#   select(name, guestCpus, memory, description, zone)
# saveRDS(x, "machine_types.rds", compress = "xz")
machines = reactive({
  # x = gcloud::gcloud_compute_machineTypes_list(
  #   zone = input$zone)
  # x = gcloud::gcloud_compute_machineTypes_list()
  # x = x[is.na(x$deprecated$state),]
  # x = x %>% 
  #   mutate(memory = round(memoryMb/1024)) %>% 
  #   select(name, guestCpus, memory, description)
  x = readRDS("machine_types.rds")
  x = x %>% 
    dplyr::filter(zone %in% input$zone)
})
output$machiner = renderUI({
  x = machines()
  x$zone = NULL
  selectizeInput("machine_type", label = "Machine Type", 
                 choices = x$name, selected = "n1-standard-4")
})
DT::renderDataTable({
  x = machines()
  x$zone = NULL
  x
}, options = list(dom = "t", autoWidth = TRUE), 
filter = "top")
```

Column {data-width=400}
-------------------------------------
### Current VMs Running

```{r}
existing_vms = reactive({
  values$refresh = isolate(values$refresh)
  the_list <- try({
    gce_list_instances(project = input$project, zone = input$zone)
  }, silent = TRUE)
  if (inherits(the_list, "try-error")) return(NULL)
  df = tibble::as_tibble(the_list)
  df = df$items
  if (!is.null(df) && nrow(df) > 0) {
    df = df %>% 
      mutate(zone = basename(zone),
             machineType = basename(machineType),
             externalIP = googleComputeEngineR:::extract_ip(the_list)
      )
    
    print_cols <- c("name","machineType","status","zone",
                    "externalIP","creationTimestamp")
    
    df = df[, print_cols]
  }
  df
})
renderTable({
  values$refresh = isolate(!values$refresh)
  input$vm_name
  df = existing_vms()
  df
})
# 

```

### Diagnostics

```{r}
run_check <- reactive({
  print("Running Checks")
  vm_good = try({
    googleComputeEngineR:::validate_vm_name(input$vm_name)
  }
  )
  if (inherits(vm_good, "try-error")) {
    print("Your VM name is not of the form lowercase with underscores")
    print(attr(vm_good, "condition"))
  } 
  check = !inherits(vm_good, "try-error")
  if (check) {
    if (input$vm_name %in% existing_vms()$name) {
      print("Your VM name is already taken, please rename")
    }
    check = check && !input$vm_name %in% existing_vms()$name
  } 
  nc_gt = function(x) {
    length(x) > 0 && nchar(x) > 0
  }
  check = check && !is.null(input$dynamic_image)
  if (check) {
    shinyjs::enable("create_image")
  } else {
    shinyjs::disable("create_image")
  }
  return(check)
})



observeEvent(input$create_image, {
  check = run_check()
  if (check) {
    print(input)
    print(input$project)
    print(input$zone)
    print(input$vm_name)
    print(input$dynamic_image)
    print(input$gb)
    region = gcloud:::region_from_zone(input$zone)
    gcloud::gcloud_compute_nat_create(region = region, verbose = 2,
                                      project = input$project)
    googleComputeEngineR::gce_global_project(project = input$project)
    vm <- googleComputeEngineR::gce_vm(
      template = "rstudio-noauth",
      name = input$vm_name,
      network = googleComputeEngineR::gce_make_network(externalIP = "none"),
      dynamic_image = input$dynamic_image,
      predefined_type = input$machine_type,
      disk_size_gb = input$gb,
      project = input$project,
      zone = input$zone)
    print(vm)
    bucket_name = paste0(input$vm_name, "-bucket")
    googleCloudStorageR::gcs_global_bucket(bucket = bucket_name)
    bucket_exists = function(bucket_name) {
      x = try({
        googleCloudStorageR::gcs_get_bucket(bucket = bucket_name)
      }, 
      silent = TRUE)
      !inherits(x, "try-error") && !is.null(x)
    }
    if (bucket_exists(bucket_name)) {
      # create a bucket
      googleCloudStorageR::gcs_create_bucket(
        name = bucket_name,
        projectId = input$project, 
        storageClass = "STANDARD"
      )
    }
    values$vm = vm
    values$refresh <- isolate(!values$refresh)
  }
})


renderPrint({
  val = run_check()
  print(paste0("If run now, the check is: ", val))
  print(values$vm)
})
```

