FROM renv-base-4.1.2-4.1.2
LABEL maintainer="Streamline_Data_Science"
RUN ["mkdir", "-m", "700", "-p", "/root/.ssh/"]
COPY [".ssh/*", "/root/.ssh/"]
RUN eval $(ssh-agent) && chmod 600 /root/.ssh/id_rsa && echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && ssh-add /root/.ssh/id_rsa
RUN ["git", "config", "--global", "user.name", "googleCloudRunner"]
RUN ["git", "config", "--global", "user.email", "cr_buildstep_gitsetup@googleCloudRunner.com"]
RUN R -f /package_scripts/install_deps.R
RUN source /package_scripts/check_package.sh
WORKDIR ./
CMD ["R"]
