FROM rocker/shiny

RUN apt-get -qq update 

# need for Docker
RUN apt-get install -y --no-install-recommends apt-utils

RUN apt-get install -y libgit2-dev cargo libssl-dev zlib1g-dev python libv8-dev pandoc pandoc-citeproc libgeos-dev libgeos++-dev default-jre-headless libharfbuzz-dev 

RUN apt-get install -y libgl1-mesa-dev make libmagic-dev gdal-bin libxml2-dev libmagick++-dev libfribidi-dev libproj-dev libgdal-dev libsodium-dev libcairo2-dev imagemagick libicu-dev 

RUN apt-get install -y libudunits2-dev libgmp-dev libcurl4-openssl-dev libmysqlclient-dev libtiff-dev libpng-dev libglu1-mesa-dev libapparmor-dev libglpk-dev git-core

RUN apt-get install -y apt-transport-https ca-certificates gnupg curl


RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

RUN apt-get -qq update && apt-get install -y google-cloud-sdk

RUN install2.r -r https://bioconductor.org/packages/3.13/bioc -r https://bioconductor.org/packages/3.13/data/annotation -r https://bioconductor.org/packages/3.13/data/experiment -r https://bioconductor.org/packages/3.13/workflows -r https://bioconductor.org/packages/3.13/books -r https://cloud.r-project.org remotes dplyr DT flexdashboard gargle rmarkdown shiny shinyjs tibble

RUN installGithub.r muschellij2/googleAuthR@b34eb02 muschellij2/googleCloudRunner@4e3ce75 cloudyr/googleComputeEngineR@bf4e5e7333ae331332b6df71799b6bbcf0acee5c

COPY check_remotes_version.R /
COPY install_packages_directory.R /
COPY packages /packages

# fix due to https://github.com/r-lib/remotes/pull/630
RUN Rscript /check_remotes_version.R

RUN Rscript /install_packages_directory.R

RUN rm -rf /packages

COPY apps/ /srv/shiny-server/

EXPOSE 3838
EXPOSE 8787

CMD ["/init"]
