# syntax=docker/dockerfile:experimental
FROM us-east4-docker.pkg.dev/streamline-resources/streamline-docker-repo/streamliner
# See https://stackoverflow.com/questions/18136389/using-ssh-keys-inside-docker-container

COPY check_remotes_version.R /
COPY install_packages_directory.R /
COPY packages /packages

# fix due to https://github.com/r-lib/remotes/pull/630
RUN Rscript /check_remotes_version.R

RUN Rscript /install_packages_directory.R

RUN rm -rf /packages


CMD ["/init"]
