FROM us-docker.pkg.dev/streamline-resources/streamline-private-repo/streamliner:latest
LABEL maintainer="jupyter"
COPY ["check_remotes_version.R", "/"]
CMD ["R", "--vanilla", "-f", "/check_remotes_version.R"]
RUN ["mkdir", "-m", "700", "-p", "/root/.ssh/"]
COPY [".ssh/*", "/root/.ssh/"]
RUN eval $(ssh-agent) && chmod 600 /root/.ssh/id_rsa && echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config && ssh-add /root/.ssh/id_rsa
RUN ["git", "config", "--global", "user.name", "googleCloudRunner"]
RUN ["git", "config", "--global", "user.email", "cr_buildstep_gitsetup@googleCloudRunner.com"]
RUN R -e "remotes::install_git(c('git@github.com:StreamlineDataScience/metagce'), git = 'external')"
RUN R -e "remotes::install_git(c('git@github.com:StreamlineDataScience/gcloud'), git = 'external')"
RUN R -e "remotes::install_git(c('git@github.com:StreamlineDataScience/trailrun'), git = 'external')"
RUN R -e "remotes::install_git(c('git@github.com:StreamlineDataScience/streamliner'), git = 'external')"
RUN R -e "remotes::install_git(c('git@github.com:StreamlineDataScience/streamverse'), git = 'external')"
RUN ["rm", "-rf", "/root/.ssh/*"]
WORKDIR /payload/
CMD ["R"]
