FROM rocker/verse

RUN apt-get -qqy update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -qqy \
        openssh-client \
        qpdf
        
# same as streamliner
COPY scripts /streamline_scripts
RUN chmod +x /streamline_scripts/*.sh

RUN /streamline_scripts/install_3rd_party.sh

RUN /streamline_scripts/install_3rd_party_extensions.sh

RUN /streamline_scripts/install_odbc_drivers.sh

# I don't want warnings to be errors
ENV R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

## Install gargle to make sure
RUN install2.r --error \ 
    gargle

## Install packages from CRAN
#    googleAuthR \ 
RUN install2.r --error \ 
    googleAnalyticsR \ 
    searchConsoleR \ 
    googleCloudRunner \
    googleCloudStorageR \
    bigQueryR \ 
    clock \
    bigrquery \ 
    sp \
    geosphere \ 
    fuzzyjoin \ 
    flexdashboard \
    zip \
## install Github packages
    && installGithub.r MarkEdmondson1234/youtubeAnalyticsR \
                       MarkEdmondson1234/googleID \
                       muschellij2/googleAuthR \
                       cloudyr/googleCloudStorageR \
                       cloudyr/googleComputeEngineR \
## clean up
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

                       # MarkEdmondson1234/googleCloudRunner 
                       
COPY Rprofile.site /usr/local/lib/R/etc/Rprofile.site


# need this because gargle caches
RUN mkdir -p ~/.cache/gargle
RUN chmod 777 ~/.cache/gargle

RUN /streamline_scripts/install_gcloud.sh

RUN /rocker_scripts/install_shiny_server.sh


## in UNSTABLE, we will install everything from source by default:
ENV CRAN=https://cran.r-project.org
## Add a default CRAN mirror
RUN echo "options(repos = c(CRAN = '${CRAN}'), download.file.method = 'libcurl')" >> ${R_HOME}/etc/Rprofile.site

EXPOSE 8787
EXPOSE 3838
CMD ["/init"]


# EVERYTHING UP to this is all good to make it's own docker
