FROM us-east4-docker.pkg.dev/streamline-resources/streamline-private-repo/streamliner

# need this because gargle caches
RUN mkdir -p ~/.cache/gargle
RUN chmod 777 ~/.cache/gargle

RUN mkdir -p /.cache/gargle
RUN chmod 777 /.cache/gargle

# I don't want warnings to be errors
ENV R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

##########################################################
# TODO - gut above, tag and proper register
##########################################################

RUN ls
COPY token.rds /token.rds
COPY package /package


# SSH AUTH and GITHUB
# just going to add this via volumes
# COPY ~/.ssh/id_rsa ~/.ssh/id_rsa

# get gpat and pass using 
# --build-arg GPAT=`gcloud secrets versions access latest --secret=SECRETNAME`
# need github_pat for remotes install
# Can't use `cat` as per https://stackoverflow.com/questions/34911622/dockerfile-set-env-to-result-of-command
ARG GPAT
ENV GITHUB_PAT=$GPAT 


# remotes::system_requirements("ubuntu")
          
# this is because it's standard to go in "package"
RUN Rscript -e "remotes::install_local('package', upgrade = FALSE)"

# GCLOUD AUTH
# as per https://cloud.google.com/build/docs/build-config-file-schema#volumes
# workspace already mounted
# COPY service_account.json /service_account.json
# COPY client.json /client.json

# COPY .Renviron ~/.Renviron
#RUN echo "GAR_CLIENT_JSON=client.json" >> /.Renviron
#RUN echo "GAR_AUTH_FILE=service_account.json" >> /.Renviron
#RUN echo "GCE_AUTH_FILE=service_account.json" >> /.Renviron


CMD ["/init"]
