FROM us-docker.pkg.dev/streamline-resources/streamline-private-repo/renv-base-4.1.1
LABEL maintainer="Streamline_Data_Science"
ENV _R_CHECK_CRAN_INCOMING_="false"
COPY ["package_scripts", "/package_scripts"]
RUN chmod +x /package_scripts/*
RUN ["/rocker_scripts/install_python.sh"]
RUN ["python -m pip install numpy --force-reinstall --no-binary numpy"]
WORKDIR ./
CMD ["R"]
