FROM gcr.io/gcer-public/persistent-rstudio

# same as streamliner
COPY scripts /streamline_scripts
RUN chmod +x /streamline_scripts/*.sh

RUN /streamline_scripts/install_3rd_party.sh

RUN /streamline_scripts/install_odbc_drivers.sh

RUN /streamline_scripts/rstudio_no_login.sh


# SSH AUTH and GITHUB
COPY ~/.ssh/id_rsa ~/.ssh/id_rsa

# get gpat and pass using 
# --build-arg GPAT=`gcloud secrets versions access latest --secret=SECRETNAME`
# need github_pat for remotes install
ARG GPAT
ENV GITHUB_PAT=${GPAT}

# 
ARG PACKAGE_NAME
ENV PACKAGE=${PACKAGE_NAME}

RUN Rscript -e "remotes::install_github(\"${PACKAGE}\")"

CMD ["/init"]