# syntax=docker/dockerfile:experimental
FROM us-docker.pkg.dev/streamline-resources/streamline-private-repo/streamliner-packages

RUN install2.r --error \ 
    shiny \
    shinydashboard \
    DT \
    flexdashboard \
    shinyjs 

RUN Rscript -e "remotes::install_github('muschellij2/googleCloudRunner')"
RUN Rscript -e "remotes::install_github('muschellij2/googleComputeEngineR')"


COPY apps/ /srv/shiny-server/
RUN cat /srv/shiny-server/create_vm/index.Rmd

EXPOSE 3838
EXPOSE 8787

CMD ["/init"]
